### ISSUE TITLE
kill the plugin

### ISSUE THREAD

**Issue by LukeRasMEL** [dorumrr/npmjs-cordova-honeywell-scanner-simplified#1]
Everything works well - My app just seems to be slowing down as I process more scans with the function like its holding cache or opening multiple instances. 
We are currently calling on the listen function every scan initiation.  Is there any way to release or kill the plugin after the scan data so that we dont hold it open or initiate multiple instances.

**Comment by dorumrr** [comment]
Hi,

I have published an update that includes explicit methods and proper documentation in order to "kill" the plugin by calling .release() when capturing the data from the barcode scanner when no longer needed. Please check the documentation and make sure you're installing the latest version of the plugin, currently 1.3.0
